--Generated by Map Resource Generator by miki_cz. | mshost.cz ;)
song = false
water = false
sky = false
vodar, vodag, vodab = 39, 111, 241
oblohar, oblohag, oblohab, oblohar2, oblohag2, oblohab2 = 250,0,0,250,0,0
lig1, lig2, lig3 = 255,0,0
messages = false
msg1 = ''
msg2 = ''
msg3 = ''
msg4 = ''
msg5 = ''
if messages then
if not msg1 == "" then
outputChatBox(msg1, 255, 0, 0, true)
end
if not msg2 == "" then
outputChatBox(msg2, 255, 0, 0, true)
end
if not msg3 == "" then
outputChatBox(msg3, 255, 0, 0, true)
end
if not msg4 == "" then
outputChatBox(msg4, 255, 0, 0, true)
end
if not msg5 == "" then
outputChatBox(msg5, 255, 0, 0, true)
end
end

if song then

function startMusic()
    setRadioChannel(0)
    song = playSound("song.mp3",true)
	outputChatBox("#FFFFFFPress #00FFFF'M'#FFFFFF to toggle the music On/Off.", 27, 89, 224, true)
end

function makeRadioStayOff()
    setRadioChannel(0)
    cancelEvent()
end

function toggleSong()
    if not songOff then
	    setSoundVolume(song,0)
		songOff = true
		removeEventHandler("onClientPlayerRadioSwitch",getRootElement(),makeRadioStayOff)
	else
	    setSoundVolume(song,1)
		songOff = false
		setRadioChannel(0)
		addEventHandler("onClientPlayerRadioSwitch",getRootElement(),makeRadioStayOff)
	end
end

addEventHandler("onClientResourceStart",getResourceRootElement(getThisResource()),startMusic)
addEventHandler("onClientPlayerRadioSwitch",getRootElement(),makeRadioStayOff)
addEventHandler("onClientPlayerVehicleEnter",getRootElement(),makeRadioStayOff)
addCommandHandler("mkmap1_racetheme",toggleSong)
bindKey("m","down","mkmap1_racetheme")
end

if water then
setWaterColor(vodar, vodag, vodab)
end

if sky then
setSkyGradient(oblohar, oblohag, oblohab, oblohar2, oblohag2, oblohab2)
end

function doThis()
if lights then
local auta = getElementsByType("vehicle")
	
	for vehicleKey, vehicleValue in ipairs(auta) do
	setVehicleHeadLightColor(vehicleValue, lig1, lig2, lig3)
	end
end
end

setTimer(doThis, 5000, 2)

